# The name of this workflow
name: Update README.md

# When a push is made to the main branch, run this workflow
on:
  push:
    branches: [main]
 
# Create a development environment
jobs:
  build:

    # Run the development environment on the latest version of Ubuntu OS
    runs-on: ubuntu-latest
    steps:
    # Make the repo available
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      # Install Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8  
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        # Enable pip caching
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      # Install pip and use pip to install third-party dependencies required to run the program
      run: |
        python -m pip install --upgrade pip
    - name: Run python script to update README.md
      # Run the program        
      run: python update.py
    - name: Commit new README.md
      # Provide git credentials and commit the updated README.md
      run: |
        git config --local user.email "kthrnmichel@gmail.com"
        git config --local user.name "KatherineMichel"
        git commit -am "Update README.md"
    # Push the changes, using GitHub Push Action, and a GITHUB_TOKEN
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
        branch: ${{ github.ref }}
